# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QCM_GUI_test6.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 822)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/rc/logo_2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.groupBox_settings = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_settings.sizePolicy().hasHeightForWidth())
        self.groupBox_settings.setSizePolicy(sizePolicy)
        self.groupBox_settings.setMinimumSize(QtCore.QSize(240, 0))
        self.groupBox_settings.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_settings.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox_settings.setObjectName("groupBox_settings")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_settings)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_runstop = QtWidgets.QPushButton(self.groupBox_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_runstop.sizePolicy().hasHeightForWidth())
        self.pushButton_runstop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_runstop.setFont(font)
        self.pushButton_runstop.setStyleSheet("#pushButton_runstop\n"
"{\n"
"background-color: green;\n"
"}\n"
"\n"
"#pushButton_runstop:checked\n"
"{\n"
"background-color: red;\n"
"}")
        self.pushButton_runstop.setCheckable(True)
        self.pushButton_runstop.setObjectName("pushButton_runstop")
        self.horizontalLayout_9.addWidget(self.pushButton_runstop)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.tabWidget_settings = QtWidgets.QTabWidget(self.groupBox_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_settings.sizePolicy().hasHeightForWidth())
        self.tabWidget_settings.setSizePolicy(sizePolicy)
        self.tabWidget_settings.setAutoFillBackground(False)
        self.tabWidget_settings.setObjectName("tabWidget_settings")
        self.tab_settings_control = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_settings_control.sizePolicy().hasHeightForWidth())
        self.tab_settings_control.setSizePolicy(sizePolicy)
        self.tab_settings_control.setObjectName("tab_settings_control")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_settings_control)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_settings_harmonics = QtWidgets.QGroupBox(self.tab_settings_control)
        self.groupBox_settings_harmonics.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_settings_harmonics.sizePolicy().hasHeightForWidth())
        self.groupBox_settings_harmonics.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_settings_harmonics.setFont(font)
        self.groupBox_settings_harmonics.setFlat(True)
        self.groupBox_settings_harmonics.setCheckable(False)
        self.groupBox_settings_harmonics.setObjectName("groupBox_settings_harmonics")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_settings_harmonics)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.groupBox_settings_harmonics)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_23.addWidget(self.label_9)
        self.comboBox_settings_control_scanmode = QtWidgets.QComboBox(self.groupBox_settings_harmonics)
        self.comboBox_settings_control_scanmode.setObjectName("comboBox_settings_control_scanmode")
        self.horizontalLayout_23.addWidget(self.comboBox_settings_control_scanmode)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_startf9 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_startf9.setObjectName("lineEdit_startf9")
        self.gridLayout.addWidget(self.lineEdit_startf9, 5, 1, 1, 1)
        self.checkBox_harm11 = QtWidgets.QCheckBox(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_harm11.sizePolicy().hasHeightForWidth())
        self.checkBox_harm11.setSizePolicy(sizePolicy)
        self.checkBox_harm11.setObjectName("checkBox_harm11")
        self.gridLayout.addWidget(self.checkBox_harm11, 6, 0, 1, 1)
        self.pushButton_cntr11 = QtWidgets.QPushButton(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cntr11.sizePolicy().hasHeightForWidth())
        self.pushButton_cntr11.setSizePolicy(sizePolicy)
        self.pushButton_cntr11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_cntr11.setObjectName("pushButton_cntr11")
        self.gridLayout.addWidget(self.pushButton_cntr11, 6, 3, 1, 1)
        self.lineEdit_startf11 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_startf11.setObjectName("lineEdit_startf11")
        self.gridLayout.addWidget(self.lineEdit_startf11, 6, 1, 1, 1)
        self.lineEdit_endf9 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_endf9.setObjectName("lineEdit_endf9")
        self.gridLayout.addWidget(self.lineEdit_endf9, 5, 2, 1, 1)
        self.lineEdit_endf11 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_endf11.setObjectName("lineEdit_endf11")
        self.gridLayout.addWidget(self.lineEdit_endf11, 6, 2, 1, 1)
        self.pushButton_cntr9 = QtWidgets.QPushButton(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cntr9.sizePolicy().hasHeightForWidth())
        self.pushButton_cntr9.setSizePolicy(sizePolicy)
        self.pushButton_cntr9.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_cntr9.setObjectName("pushButton_cntr9")
        self.gridLayout.addWidget(self.pushButton_cntr9, 5, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_settings_harmonics)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 1, 1, 1)
        self.lineEdit_startf1 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_startf1.setObjectName("lineEdit_startf1")
        self.gridLayout.addWidget(self.lineEdit_startf1, 1, 1, 1, 1)
        self.pushButton_cntr1 = QtWidgets.QPushButton(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cntr1.sizePolicy().hasHeightForWidth())
        self.pushButton_cntr1.setSizePolicy(sizePolicy)
        self.pushButton_cntr1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_cntr1.setStyleSheet("")
        self.pushButton_cntr1.setObjectName("pushButton_cntr1")
        self.gridLayout.addWidget(self.pushButton_cntr1, 1, 3, 1, 1)
        self.lineEdit_startf3 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_startf3.setObjectName("lineEdit_startf3")
        self.gridLayout.addWidget(self.lineEdit_startf3, 2, 1, 1, 1)
        self.checkBox_harm5 = QtWidgets.QCheckBox(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_harm5.sizePolicy().hasHeightForWidth())
        self.checkBox_harm5.setSizePolicy(sizePolicy)
        self.checkBox_harm5.setObjectName("checkBox_harm5")
        self.gridLayout.addWidget(self.checkBox_harm5, 3, 0, 1, 1)
        self.checkBox_harm1 = QtWidgets.QCheckBox(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_harm1.sizePolicy().hasHeightForWidth())
        self.checkBox_harm1.setSizePolicy(sizePolicy)
        self.checkBox_harm1.setObjectName("checkBox_harm1")
        self.gridLayout.addWidget(self.checkBox_harm1, 1, 0, 1, 1)
        self.lineEdit_startf5 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_startf5.setObjectName("lineEdit_startf5")
        self.gridLayout.addWidget(self.lineEdit_startf5, 3, 1, 1, 1)
        self.lineEdit_endf5 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_endf5.setObjectName("lineEdit_endf5")
        self.gridLayout.addWidget(self.lineEdit_endf5, 3, 2, 1, 1)
        self.pushButton_cntr5 = QtWidgets.QPushButton(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cntr5.sizePolicy().hasHeightForWidth())
        self.pushButton_cntr5.setSizePolicy(sizePolicy)
        self.pushButton_cntr5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_cntr5.setObjectName("pushButton_cntr5")
        self.gridLayout.addWidget(self.pushButton_cntr5, 3, 3, 1, 1)
        self.checkBox_harm7 = QtWidgets.QCheckBox(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_harm7.sizePolicy().hasHeightForWidth())
        self.checkBox_harm7.setSizePolicy(sizePolicy)
        self.checkBox_harm7.setObjectName("checkBox_harm7")
        self.gridLayout.addWidget(self.checkBox_harm7, 4, 0, 1, 1)
        self.lineEdit_endf1 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_endf1.setObjectName("lineEdit_endf1")
        self.gridLayout.addWidget(self.lineEdit_endf1, 1, 2, 1, 1)
        self.lineEdit_startf7 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_startf7.setObjectName("lineEdit_startf7")
        self.gridLayout.addWidget(self.lineEdit_startf7, 4, 1, 1, 1)
        self.lineEdit_endf7 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_endf7.setObjectName("lineEdit_endf7")
        self.gridLayout.addWidget(self.lineEdit_endf7, 4, 2, 1, 1)
        self.pushButton_cntr3 = QtWidgets.QPushButton(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cntr3.sizePolicy().hasHeightForWidth())
        self.pushButton_cntr3.setSizePolicy(sizePolicy)
        self.pushButton_cntr3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_cntr3.setObjectName("pushButton_cntr3")
        self.gridLayout.addWidget(self.pushButton_cntr3, 2, 3, 1, 1)
        self.checkBox_harm3 = QtWidgets.QCheckBox(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_harm3.sizePolicy().hasHeightForWidth())
        self.checkBox_harm3.setSizePolicy(sizePolicy)
        self.checkBox_harm3.setObjectName("checkBox_harm3")
        self.gridLayout.addWidget(self.checkBox_harm3, 2, 0, 1, 1)
        self.pushButton_cntr7 = QtWidgets.QPushButton(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cntr7.sizePolicy().hasHeightForWidth())
        self.pushButton_cntr7.setSizePolicy(sizePolicy)
        self.pushButton_cntr7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_cntr7.setObjectName("pushButton_cntr7")
        self.gridLayout.addWidget(self.pushButton_cntr7, 4, 3, 1, 1)
        self.lineEdit_endf3 = QtWidgets.QLineEdit(self.groupBox_settings_harmonics)
        self.lineEdit_endf3.setObjectName("lineEdit_endf3")
        self.gridLayout.addWidget(self.lineEdit_endf3, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_settings_harmonics)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.checkBox_harm9 = QtWidgets.QCheckBox(self.groupBox_settings_harmonics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_harm9.sizePolicy().hasHeightForWidth())
        self.checkBox_harm9.setSizePolicy(sizePolicy)
        self.checkBox_harm9.setObjectName("checkBox_harm9")
        self.gridLayout.addWidget(self.checkBox_harm9, 5, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_settings_harmonics)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem2)
        self.groupBox_settingstime = QtWidgets.QGroupBox(self.tab_settings_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_settingstime.sizePolicy().hasHeightForWidth())
        self.groupBox_settingstime.setSizePolicy(sizePolicy)
        self.groupBox_settingstime.setFlat(True)
        self.groupBox_settingstime.setObjectName("groupBox_settingstime")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_settingstime)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_refreshresolution = QtWidgets.QLineEdit(self.groupBox_settingstime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_refreshresolution.sizePolicy().hasHeightForWidth())
        self.lineEdit_refreshresolution.setSizePolicy(sizePolicy)
        self.lineEdit_refreshresolution.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_refreshresolution.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_refreshresolution.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_refreshresolution.setObjectName("lineEdit_refreshresolution")
        self.gridLayout_3.addWidget(self.lineEdit_refreshresolution, 5, 2, 1, 1)
        self.lineEdit_recordinterval = QtWidgets.QLineEdit(self.groupBox_settingstime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_recordinterval.sizePolicy().hasHeightForWidth())
        self.lineEdit_recordinterval.setSizePolicy(sizePolicy)
        self.lineEdit_recordinterval.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_recordinterval.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_recordinterval.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_recordinterval.setObjectName("lineEdit_recordinterval")
        self.gridLayout_3.addWidget(self.lineEdit_recordinterval, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 5, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_settingstime)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_settingstime)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lineEdit_reftime = QtWidgets.QLineEdit(self.groupBox_settingstime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_reftime.sizePolicy().hasHeightForWidth())
        self.lineEdit_reftime.setSizePolicy(sizePolicy)
        self.lineEdit_reftime.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_reftime.setObjectName("lineEdit_reftime")
        self.horizontalLayout_8.addWidget(self.lineEdit_reftime)
        self.pushButton_resetreftime = QtWidgets.QPushButton(self.groupBox_settingstime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_resetreftime.sizePolicy().hasHeightForWidth())
        self.pushButton_resetreftime.setSizePolicy(sizePolicy)
        self.pushButton_resetreftime.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_resetreftime.setObjectName("pushButton_resetreftime")
        self.horizontalLayout_8.addWidget(self.pushButton_resetreftime)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 5)
        self.label = QtWidgets.QLabel(self.groupBox_settingstime)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 4, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_settingstime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 1, 1, 1)
        self.lineEdit_scaninterval = QtWidgets.QLineEdit(self.groupBox_settingstime)
        self.lineEdit_scaninterval.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_scaninterval.setReadOnly(True)
        self.lineEdit_scaninterval.setObjectName("lineEdit_scaninterval")
        self.gridLayout_3.addWidget(self.lineEdit_scaninterval, 6, 2, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_settingstime)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem5)
        self.groupBox_settings_fitting = QtWidgets.QGroupBox(self.tab_settings_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_settings_fitting.sizePolicy().hasHeightForWidth())
        self.groupBox_settings_fitting.setSizePolicy(sizePolicy)
        self.groupBox_settings_fitting.setFlat(True)
        self.groupBox_settings_fitting.setObjectName("groupBox_settings_fitting")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_settings_fitting)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_showchi = QtWidgets.QCheckBox(self.groupBox_settings_fitting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_showchi.sizePolicy().hasHeightForWidth())
        self.checkBox_showchi.setSizePolicy(sizePolicy)
        self.checkBox_showchi.setObjectName("checkBox_showchi")
        self.gridLayout_2.addWidget(self.checkBox_showchi, 4, 0, 1, 1)
        self.checkBox_dynamicfit = QtWidgets.QCheckBox(self.groupBox_settings_fitting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_dynamicfit.sizePolicy().hasHeightForWidth())
        self.checkBox_dynamicfit.setSizePolicy(sizePolicy)
        self.checkBox_dynamicfit.setChecked(True)
        self.checkBox_dynamicfit.setObjectName("checkBox_dynamicfit")
        self.gridLayout_2.addWidget(self.checkBox_dynamicfit, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_settings_fitting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.comboBox_fitfactor = QtWidgets.QComboBox(self.groupBox_settings_fitting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_fitfactor.sizePolicy().hasHeightForWidth())
        self.comboBox_fitfactor.setSizePolicy(sizePolicy)
        self.comboBox_fitfactor.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_fitfactor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_fitfactor.setObjectName("comboBox_fitfactor")
        self.horizontalLayout_7.addWidget(self.comboBox_fitfactor)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.checkBox_showsusceptance = QtWidgets.QCheckBox(self.groupBox_settings_fitting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_showsusceptance.sizePolicy().hasHeightForWidth())
        self.checkBox_showsusceptance.setSizePolicy(sizePolicy)
        self.checkBox_showsusceptance.setChecked(False)
        self.checkBox_showsusceptance.setObjectName("checkBox_showsusceptance")
        self.gridLayout_2.addWidget(self.checkBox_showsusceptance, 2, 0, 1, 1)
        self.checkBox_showpolar = QtWidgets.QCheckBox(self.groupBox_settings_fitting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_showpolar.sizePolicy().hasHeightForWidth())
        self.checkBox_showpolar.setSizePolicy(sizePolicy)
        self.checkBox_showpolar.setObjectName("checkBox_showpolar")
        self.gridLayout_2.addWidget(self.checkBox_showpolar, 3, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_settings_fitting)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem7)
        self.groupBox_settings_output = QtWidgets.QGroupBox(self.tab_settings_control)
        self.groupBox_settings_output.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_settings_output.sizePolicy().hasHeightForWidth())
        self.groupBox_settings_output.setSizePolicy(sizePolicy)
        self.groupBox_settings_output.setFlat(True)
        self.groupBox_settings_output.setObjectName("groupBox_settings_output")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_settings_output)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_datafilestr = QtWidgets.QLineEdit(self.groupBox_settings_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_datafilestr.sizePolicy().hasHeightForWidth())
        self.lineEdit_datafilestr.setSizePolicy(sizePolicy)
        self.lineEdit_datafilestr.setText("")
        self.lineEdit_datafilestr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_datafilestr.setReadOnly(True)
        self.lineEdit_datafilestr.setObjectName("lineEdit_datafilestr")
        self.horizontalLayout_5.addWidget(self.lineEdit_datafilestr)
        self.pushButton_gotofolder = QtWidgets.QPushButton(self.groupBox_settings_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_gotofolder.sizePolicy().hasHeightForWidth())
        self.pushButton_gotofolder.setSizePolicy(sizePolicy)
        self.pushButton_gotofolder.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_gotofolder.setObjectName("pushButton_gotofolder")
        self.horizontalLayout_5.addWidget(self.pushButton_gotofolder)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_newdata = QtWidgets.QPushButton(self.groupBox_settings_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_newdata.sizePolicy().hasHeightForWidth())
        self.pushButton_newdata.setSizePolicy(sizePolicy)
        self.pushButton_newdata.setObjectName("pushButton_newdata")
        self.horizontalLayout_6.addWidget(self.pushButton_newdata)
        self.pushButton_appenddata = QtWidgets.QPushButton(self.groupBox_settings_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_appenddata.sizePolicy().hasHeightForWidth())
        self.pushButton_appenddata.setSizePolicy(sizePolicy)
        self.pushButton_appenddata.setObjectName("pushButton_appenddata")
        self.horizontalLayout_6.addWidget(self.pushButton_appenddata)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addWidget(self.groupBox_settings_output)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.groupBox_settings_harmonics.raise_()
        self.groupBox_settingstime.raise_()
